### ISSUE TITLE
Meshes in urdf begin with ""package://JACO3_URDF_V10..." in the kortex_description package

### ISSUE THREAD

**Issue by AshisGhosh** [Kinovarobotics/ros_kortex#1]
The urdf and meshes are located in the `kortex_description` package. However, the urdf specifies for the meshes to be loaded from a `JACO_URDF_V10` package.

**Comment by thieraufc** [comment]
Hi @alexvannobel , are you able to offer a timeline on the release of 1.1.6? I would also be interested in having functioning launch files for the gen3 arm.

**Comment by alexvannobel** [comment]
Hi @thieraufc !
The software package needed additional testing before release, it's why it was delayed.
Unfortunately, I can't provide you with a specific date as the release will depend on the test results.
As for the launch files, I am currently working on them! They will be uploaded with release 1.1.6.

**Comment by alexvannobel** [comment]
Hi,

Version 1.1.6 was just released and the JACO_URDF_V10 package is now named kortex_description.
As for the launch files, they should be uploaded to the kinetic-devel branch in the upcoming days.
