### ISSUE TITLE
Function to return if gripper is connected or not

### ISSUE THREAD

**Issue by rshum19** [Kinovarobotics/ros_kortex#107]
Hi,

Does the API provide a method to find if a gripper is connected or not to the Gen3?

Thank you,

**Comment by alexvannobel** [comment]
Hi @rshum19 ,

The API provides a method to find out what is the user-specified gripper configuration, and the kortex_driver checks [if that variable matches the one supplied in the launch file](https://github.com/Kinovarobotics/ros_kortex/blob/kinetic-devel/kortex_driver/src/non-generated/driver/kortex_arm_driver.cpp#L320-L361) via the `Kinova::Api::Base::GetProductConfiguration()` method.

Gen3 users can change this value in the WebApp, under Configuration -> Robot -> Product -> End Effector Type:

![image](https://user-images.githubusercontent.com/41082816/87547018-7a647300-c678-11ea-96ea-9ded80e9309d.png)

The arm doesn't have a method to actually get the **connected** gripper type, or if one is connected at all.

Hope this answers your question.
I'll close the issue, but don't hesitate to reopen or create a new one if you have other questions.

Best,
Alex
