### ISSUE TITLE
Use standard ROS naming for links

### ISSUE THREAD

**Issue by Achllle** [Kinovarobotics/ros_kortex#12]
Currently link names are in the style of 'ForeArm_Link' and joints are in the more sensible form of 'ActuatorN'. [REP199](https://github.com/gavanderhoorn/rep/blob/coord_frames_ind_robots/rep-xxxx.rst) (unmerged) recommends link names à la 'link_N' and 'joint_N' (lowercase only!). `base_link` is already in the right format, but the following links aren't and use a different convention.

If this is just a change on the ROS repo, happy to open a PR myself to change this. In any case, combining camel casing with underscores is massive cringe to anyone software.

**Comment by alexvannobel** [comment]
Hi @Achllle ,

Thanks for your feedback! I opened a PR to the kinetic-devel branch to change the joints and links naming.
