### ISSUE TITLE
Contact detection

### ISSUE THREAD

**Issue by phuicy** [Kinovarobotics/ros_kortex#120]
Hi,

Is there a method for detecting method the manipulator is contacting any external objects?

thanks,
Guy

**Comment by alexvannobel** [comment]
Hi @phuicy ,
Sorry for the long delay.

Unfortunately, no we don't provide a method to detect if the end effector is contacting an external object. 
However, you could try to use the `external_tool_wrench_force*` and `external_tool_wrench_torque*` from the Base feedback to detect such events.

Cheers,
Alex

**Comment by phuicy** [comment]
That is perfect.
