### ISSUE TITLE
A problem with conanfile.py

### ISSUE THREAD

**Issue by wyh96** [Kinovarobotics/ros_kortex#139]
Hello, I encountered an error with catkin make.
![image](https://user-images.githubusercontent.com/76680075/103197974-1120a580-4922-11eb-9932-56b83f384b69.png)
I checked conanfile.py. It hadn't been touched. 
The ros package worked well last week. Could you please help me to solve the problem?

**Comment by polthergeist** [comment]
Hi @wyh96 , do you still have that problem? On my side it is working well.

**Comment by alexvannobel** [comment]
I also don't have the problem.
I looks like a connection problem to me : either our Artifactory server was momentarily down or your connection was faulty.

**Comment by wyh96** [comment]
Hello, I used backup files and it works.

**Comment by polthergeist** [comment]
Ok, sounds good. I will close the issue but if you have any other problem don't hesitate to open a new one.

**Comment by polthergeist** [comment]
Probably a connection problem.

**Comment by wyh96** [comment]
thank you!
