### ISSUE TITLE
Orientation change of end-effector frame

### ISSUE THREAD

**Issue by Achllle** [Kinovarobotics/ros_kortex#17]
#13 (kinetic-devel) rotated the frame for the end-effector link (see pictures). I didn't see this being referenced in the PR, so I'm assuming this happened by mistake.

old: `urdf/JACO3_URDF_V11.urdf`:
![oldframes](https://user-images.githubusercontent.com/14060847/56700767-c6f91280-66b0-11e9-85c8-a127bce9f7c0.png)

new: `robots/gen3.xacro`:
![newframes](https://user-images.githubusercontent.com/14060847/56700765-c3658b80-66b0-11e9-9326-05502d4dad00.png)

Happy to open a PR to fix if this is a bug, not a feature.

**Comment by alexvannobel** [comment]
Hi @Achllle ,

Thanks a lot for the feedback. It was indeed a bug, not a feature. 

Cheers,
Alex
