### ISSUE TITLE
Setting prefix breaks joint_state_publisher

### ISSUE THREAD

**Issue by phuicy** [Kinovarobotics/ros_kortex#188]
## Description

If a prefix is set, the joint_state_publisher publishes all zeroes, base_feedback has correct values. joint_state_publisher seems to be confused about the joints to copy.

## Version

ROS distribution : Noetic

Branch and commit you are using : master

## Steps to reproduce

1. Set prefix in the launch
2. Launch and echo joint_state

## Expected behavior

joint_state_publisher to republish base_feedback/joint_state 

## Any other information

This breaks all moveit features.

**Comment by phuicy** [comment]
Actually the prefix seems to be applied twice somewhere: 
![image](https://user-images.githubusercontent.com/4666094/132186120-72a86077-6074-4f08-8409-a44a3f48d791.png)
The prefix in the lanuch ```<arg name="prefix" default="prefix_"/>```

**Comment by phuicy** [comment]
https://github.com/Kinovarobotics/ros_kortex/blob/a334ce2a9fcbec12b27012f77183a81a75ec6e6e/kortex_driver/src/non-generated/driver/kortex_arm_driver.cpp#L655

and

https://github.com/Kinovarobotics/ros_kortex/blob/a334ce2a9fcbec12b27012f77183a81a75ec6e6e/kortex_driver/src/non-generated/driver/kortex_arm_driver.cpp#L666

These line seems to apply the prefix for a second time.

**Comment by phuicy** [comment]
Ok, that has fixed the joint_state_publisher. but robot_state_publisher still not outputting tf.

**Comment by felixmaisonneuve** [comment]
Hi @phuicy,

Using a prefix will break MoveIt!. If you want to use Moveit with a prefix, you will need to change its configuration and the according `.yaml` file. This is mentionned in the [readme](https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_driver#usage) inside the `prefix` bullet point. 

This is annoying and this is something that would be nice to "fix", I just did not have the time to do it yet. 

However, I don't think I have seen the prefix applied twice before. Have you changed anything in your configs?
Also, the two lines you have mentionned in `kortex_arm_driver.cpp` are not duplicating the prefix. The first puts the prefix for the actuators joints and the second one is putting the prefix for the gripper motors.

Regards,
Felix

**Comment by yukizakisoh** [comment]
I also faced the same symptom: the prefix appeared twice in base_feedback/joint_state.
Then I did the following modifications as @phuicy did, and it improved the situation.

> https://github.com/Kinovarobotics/ros_kortex/blob/a334ce2a9fcbec12b27012f77183a81a75ec6e6e/kortex_driver/src/non-generated/driver/kortex_arm_driver.cpp#L655
> 
> and
> 
> https://github.com/Kinovarobotics/ros_kortex/blob/a334ce2a9fcbec12b27012f77183a81a75ec6e6e/kortex_driver/src/non-generated/driver/kortex_arm_driver.cpp#L666
> 
> These line seems to apply the prefix for a second time.

In my environment, robot_state_publisher now works correctly, and moveit also works correctly without changing .yaml files.


## Version
ROS distribution : melodic
Branch and commit you are using : melodic-devel
using a real robot

**Comment by felixmaisonneuve** [comment]
Hi @phuicy and @yukizakisoh,

I tried the fix and I now understand what you meant. Like you both said, this will fix the prefix that is duplicated in `joint_state`. I created PR #194 about it. 
This was a known bug that was preventing moveit from working when using a prefix. I did not have to time to look into yet, so thank you for pointing it out to me. 

@phuicy you were also mentionning `robot_state_publisher` is still not outputting correctly. Can you elaborate on that?

Regards,
Felix

**Comment by phuicy** [comment]
robot_state_publisher needed to be pointed at the namespaced topic explicitly.

**Comment by felixmaisonneuve** [comment]
Hi @phuicy,

Can you please explain a bit more? 

After changing `kortex_arm_driver` to remove duplicated prefix, is there still something wrong? Should I update something else in our arm driver? 

You seemed to have fix the issue, but I am not sure what the problem was in the first place.
Can you give more details?

Thank You,
Felix

**Comment by phuicy** [comment]
@felixmaisonneuve 

https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/kortex_driver/launch/kortex_driver.launch#L106

Needs to be adapted to point Parameters robot_description (urdf map) and tf_prefix to the correct names.

**Comment by felixmaisonneuve** [comment]
@phuicy

I am not sure I fully understand what you are asking. 
The urdf map is already set at the correct param `robot_description` and there is no need to remap the parameter in the `robot_state_publisher` node. 

For the tf_prefix parameter, what should I set? From what I understand, you say I should do something like 
```
<node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher">
            <rosparam param="tf_prefix">${prefix}</rosparam>
</node>
```

Can you explain to me if this is correct and what it would bring?

Best,
Felix
