### ISSUE TITLE
kortex_examples setup.py fails due to absolute path

### ISSUE THREAD

**Issue by danielj195** [Kinovarobotics/ros_kortex#192]
## Description
The` setup.py` script located in the `kortex_examples` package causes compilation to fail because the package directory is absolute, when it should be relative
One paragraph to explain the issue
The `setup.py` script is unable to find `kortex_examples` package

## Version

ROS distribution : Noetic

Branch and commit you are using : noetic-devel 
6a1c68179c556e4e8c70c700cb36e23c9a148a1a

## Steps to reproduce
include ros_kortex as a submodule in src directory and use colcon to build

FIX:

In `kortex_examples/setup.py`, change line 6 to `package_dir={'': '..'}`

**Comment by felixmaisonneuve** [comment]
Hi @danielj195,

I don't know much about `setup.py` files, but I feel like it is correct. I don't understand why I should change it. 
This file is used by `catkin` to find the source files using the relative path `src` within the `kortex_examples` package (`kortex_examples/src`) and this is exactly where the source files are located. Looking at the [catkin documentation](https://docs.ros.org/en/api/catkin/html/user_guide/setup_dot_py.html), `setup.py` looks to be used in the same way.

Maybe it is related to `colcon` (I don't know this tool). Do you have informations or sources that could help better understand the issue?
Maybe I am missing something I don't know.

Regards,
Felix

**Comment by felixmaisonneuve** [comment]
Hi @danielj195,

Does your compilation still fail? 
I will wait a couple of days and close this issue if I don't get any answer

Best,
Felix

**Comment by danielj195** [comment]
it compiled this time, I must have not sourced or had it in the wrong directory or something. I just closed the issue
