### ISSUE TITLE
Conan SSL Certificate error

### ISSUE THREAD

**Issue by felixmaisonneuve** [Kinovarobotics/ros_kortex#198]
## Description

Conan's root certificate recently expired (2021-09-30), and, while using conan, it is possible to get an error similar to 
```
ERROR: HTTPSConnectionPool(host='artifactory.kinovaapps.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan/v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))
```
## Fix

You can get the new certificate and make conan work again by running
```
conan config install https://github.com/conan-io/conanclientcert.git
```

**Comment by filesmuggler** [comment]
I encountered this error during catkin_make. Above solution fixed the issue.
