### ISSUE TITLE
ros_control and/or moveiit integration

### ISSUE THREAD

**Issue by evankrause** [Kinovarobotics/ros_kortex#22]
I'm curious about the timeline for releasing either ros_control or MoveIt code. Any thoughts on when this might be available?

Thanks,
Evan

**Comment by alexvannobel** [comment]
Hi Evan,

We currently are working on Gazebo and MoveIt! integration coming up for the next release (somewhere around June). The ROS control integration will be the next ROS milestone after that. 
I invite you to take a look at #20 if you're interested in a third-party ROS Control implementation for the Gen3 arm.

Thanks a lot for the feedback,
Cheers,
Alex

**Comment by evankrause** [comment]
Great, thanks for the update Alex. I think I'll hold off until the next release with MoveIt! integration.
