### ISSUE TITLE
Failed requirement 'kortex_api_cpp/2.3.0-r.34@kortex/stable' from 'conanfile.py'

### ISSUE THREAD

**Issue by JingKangSun** [Kinovarobotics/ros_kortex#224]
When I do catkin_make, this error occurs. How can I solve this problem. My environment is: Ubuntu16.04, ros kinetic.

![2022-03-25 11-32-03屏幕截图](https://user-images.githubusercontent.com/89125332/160049022-49237827-2cd1-4eeb-93ba-b5ce4aa174d2.png)

Thanks!

**Comment by felixmaisonneuve** [comment]
Hi @JingKangSun 

For future references, I will link these three other issues related to conan SSL errors : 
#198 / #203 : both are the same error
#210 

In your case, I think you could try
```
conan remote remove conan-center
conan remote add conancenter https://center.conan.io --insert 1
```

This was the solution for the third issue (#210)

Best,
Felix

**Comment by JingKangSun** [comment]
Hi, @felixmaisonneuve 

Thanks for your reply, it does work！

Best, 
JingKang

**Comment by soroush-msd** [comment]
Hi, when I try the commands I get the following errors: Is there any fix to this?

parallels@ubuntu-linux-20-04-desktop:~/catkin_ws$ conan remote remove conan-center
ERROR: No remote 'conan-center' defined in remotes
parallels@ubuntu-linux-20-04-desktop:~/catkin_ws$ conan remote add conancenter https://center.conan.io --insert 1
ERROR: Remote 'conancenter' already exists in remotes (use update to modify)

**Comment by felixmaisonneuve** [comment]
Hi @soroush-msd,

Looking at the conan [documentation](https://docs.conan.io/en/latest/reference/commands/misc/remote.html), you could try adding the `--force` tag.
>Adding the --force argument to conan remote add will always work, and won’t raise an error. If an existing remote exists with that remote name or URL, it will be updated with the new information.

Best,
Felix

**Comment by soroush-msd** [comment]
Thank you @felixmaisonneuve .

Using --force tag resolved the issue.
