### ISSUE TITLE
How can I close the auto-focus of the camera?

### ISSUE THREAD

**Issue by JingKangSun** [Kinovarobotics/ros_kortex#226]
Hi,

I want to do a calibration on the camera of the kinova-gen3, however, I found that the camera open the auto-focus function.

How can I close this function?

Thanks.

**Comment by felixmaisonneuve** [comment]
Hi @JingKangSun,

I see you also have duplicated this issue in our ros_kortex_vision repo :
https://github.com/Kinovarobotics/ros_kortex_vision/issues/8

I will close this one and answer you in the other issue
