### ISSUE TITLE
kortex_driver node dies while opening/closing robotic-2f-85 gripper in gen3 

### ISSUE THREAD

**Issue by rajnishtripathi10121995** [Kinovarobotics/ros_kortex#230]
## Description
Kortex driver node dies while opening/closing robotic-2f-85 gripper in gen3 from python code. 

## Version
ros-melodic

## Error log
terminate called after throwing an instance of 'std::runtime_error'
  what():  timeout detected: BaseCyclicClient::RefreshFeedback

[ridgeback01/ridgeback01_driver-1] process has died [pid 25747, exit code -6, cmd ].

**Comment by felixmaisonneuve** [comment]
Hi @rajnishtripathi10121995,

Can you provide the full output of the terminal after your `roslaunch ...` command? 
Does this also happens in C++?
Does your gripper opens/closes a bit before crashing or your program is crashing the moment you send the gripper command?

Best,
Felix

**Comment by rajnishtripathi10121995** [comment]
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/105341076/167862243-9836b6c1-9840-48cd-a96d-4c1fdb32d39d.png)

This error occurs randomly, sometimes kortex_driver node crashes immediately after launching it. But in most cases it is crashing with opening/closing of gripper. Yes, gripper closes/opens before crashing.

**Comment by felixmaisonneuve** [comment]
`BaseCyclic` uses UDP communication, so you might be loosing packets (maybe your computer is under eavy load causing messages to be lost)

Do you know if this happens in C++ as well?
Python is slower than C++ so the feedback might not be reaching on time

**Comment by rajnishtripathi10121995** [comment]
Yes, sometimes node dies even on launching kortex_driver node, might be network issue because earlier it was working fine and my network got changed yesterday. Can this occur due to firewall in network or any other network issues?

**Comment by tohruk** [comment]
Hi,
I'm facing a similar error on a Jetson AGX Xavier like below. How can I avoid/resolve this error?

```
[ INFO] [1650899619.272744696]: 0.122271 and 0.125000
[ INFO] [1650899619.273658808]: New goal received.
[ INFO] [1650899619.275225560]: 0.122271 and 0.125000
[ INFO] [1650899619.289199128]: New goal received.
[ WARN] [1650899619.289311224]: There is already an active goal. It is being cancelled.
[ INFO] [1650899619.289359448]: Sending zero-speed Gripper Command on the robot.
[ INFO] [1650899619.498513208]: 0.122271 and 0.125000
[ INFO] [1650899619.499536632]: New goal received.
[ INFO] [1650899619.504124344]: 0.122271 and 0.125000
[ INFO] [1650899619.514520568]: New goal received.
[ WARN] [1650899619.514646904]: There is already an active goal. It is being cancelled.
[ INFO] [1650899619.514698296]: Sending zero-speed Gripper Command on the robot.
terminate called after throwing an instance of 'std::runtime_error'
  what():  timeout detected: BaseCyclicClient::RefreshFeedback

[my_gen3/my_gen3_driver-2] process has died [pid 8442, exit code -6, cmd /home/nvidia/kinova_ws/devel/lib/kortex_driver/kortex_arm_driver __name:=my_gen3_driver __log:=/home/nvidia/.ros/log/0b42934e-c4aa-11ec-956f-00044bc7bb35/my_gen3-my_gen3_driver-2.log].
log file: /home/nvidia/.ros/log/0b42934e-c4aa-11ec-956f-00044bc7bb35/my_gen3-my_gen3_driver-2*.log
```

**Comment by rajnishtripathi10121995** [comment]
I think it was network related issue in my case. Maybe due to extra network load in my computer, it fixed automatically after few days.

**Comment by felixmaisonneuve** [comment]
Hi @tohruk,

This issue is related to network/communication. 
Do you use python or C++?
Do you run your program under heavy load?
Are you running your program inside a VM?
Are you using WIFI or a wired connection?

Best,
Felix

**Comment by tohruk** [comment]
Hi @felixmaisonneuve ,

You are right. I used to put a wired network hub between the Jetson AGX Xavier and the Kinova Gen3. That was the problem and removing the network hub reduced the frequency of the issue, however, I'm still seeing the issue once in hours. I don't know how I can improve this. I may need to leave from Jetson.

**Comment by felixmaisonneuve** [comment]
Hi @tohruk,

We have a bug where the Gen3 arm disconnects from the API after multiple hours of run time (~15h). It can happen sooner or later, there is no fixed run time.

Since you mentionned your problem occurs after multiple hours, this might be it and I don't know if leaving from Jetson will help. I encourage you to try on a different platform, but I don't know if it will solve your problem. 

There is currently no fix or workaround for that bug.

I will close this issue, and if you experience any other problem, please open a new one and I will help you

Best,
Felix
