### ISSUE TITLE
MoveIT 

### ISSUE THREAD

**Issue by TropicalPenguinn** [Kinovarobotics/ros_kortex#249]
hello 

---setting----
OS: ubuntu 20.04
ROS Noetic

I tried to make my own MoveIt Configuration files with gen3_lite model. 

I loaded gen3_lite_macro.xacro URDF file into MoveIt setup Assistant but got an error as below
![image](https://user-images.githubusercontent.com/75155964/183357842-c1113d66-ae9d-406a-8240-c719ba28f731.png)

I knew from README that you made move_if_config with Moveit . but that URDF model not to be loaded. You used your own SRDF file for making move_it_config package? If then, Can I get that SRDF file if not illegal?

**Comment by felixmaisonneuve** [comment]
Hi @LeeJeongWoon-Workout,

I am not sure why the Setup Assistant is unable to locate the kortex_description package. 
Every arm's configuration as a URDF file in the [kortex_description folder](https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_description). You can find the [Gen3-lite URDF](https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_description/arms/gen3_lite/6dof/urdf) in there.
You can also generate the urdf from the xacro files using something like 
```
rosrun xacro xacro.py gen3_lite_macro.xacro > gen3_lite.urdf
```

I did not play with the Moveit Setup Assistant that much so I am not sure what the issue could be. 
Do you need to configure it to be in the workspace? Do you need to build with `catkin_make` first? Maybe source devel/setup.bash first before launching the setup assistant?

Best,
Felix

**Comment by TropicalPenguinn** [comment]
I solved my issue. I should have got into kortex_description/robot directory

**Comment by felixmaisonneuve** [comment]
Great

I will close this issue then
If you have any other question or problem, feel free to re-open the issue or open a new one

Best Regards,
Felix
