### ISSUE TITLE
pick and place example

### ISSUE THREAD

**Issue by TropicalPenguinn** [Kinovarobotics/ros_kortex#251]
hello i am doing some project using kinova_gen3_lite.

I well made cartesian motion planning using kinova_gen3_lite but got trouble with pick and place becuase there is no simple examples in ros-kortex

so would you make pick and place example for user?

**Comment by felixmaisonneuve** [comment]
Hi @LeeJeongWoon-Workout,

We do not have a dedicated pick and place example, but the Full Arm Movement example is a combination of cartesian movement, angular movement and gripper commands, which is exactly what you need to create your own pick and place example. 
You just have to adapt the example with your own cartesian positions and you will be good to go. 

Best,
Felix

**Comment by TropicalPenguinn** [comment]
Thank you good day

**Comment by TropicalPenguinn** [comment]
F
