### ISSUE TITLE
Joint Detection Errorが発生する

### ISSUE THREAD

**Issue by Miya-imslab** [Kinovarobotics/ros_kortex#252]
gen3の電源を入れたとき、status LEDが赤く光り、kinova web applicationで確認すると"Joint Detection Error"というステータスがエラーになっています。なにか解決策はありますか？

**Comment by felixmaisonneuve** [comment]
Hi @sleepysummer,

If you cannot clear the fault using the WebApp (with the "Clear Faults" button), then I would suggest you contact our support team at support@kinova.ca

Sorry,
Felix

**Comment by Miya-imslab** [comment]
"Clear Faults" buttonが見つかりません。もしかして、右上にある"Error"を開いたときの"Clear all" buttonですか？

**Comment by felixmaisonneuve** [comment]
Yes, this is the one
