### ISSUE TITLE
Cartesian reference frame

### ISSUE THREAD

**Issue by akihikoy** [Kinovarobotics/ros_kortex#26]
Hello,

I want to know which frame is the reference of the Cartesian (end effector) pose.

We can compute an end-effector pose from the current joint angles and the robot description given by the URDF.  I used KDL to compute this.  The frames can be clearly defined; the base frame is base_link, and the end-effector frame is EndEffector_Link.

On the other hand, we can also get an end-effector pose via RefreshFeedback service, which contains output.base.tool_pose_* values.
However I do not understand on which frame these values are defined.

For joint angles `q = [ 6.0369  1.0921  3.3023  4.6336  6.0416  1.182   1.5333]`,
KDL: `x = [ 0.6592  0.0651  0.1971  0.5006  0.4804  0.4949  0.5232]`
RefreshFeedback: `x = [ 0.779   0.0593  0.2015  0.5006  0.4804  0.4949  0.5232]`
(Note: RefreshFeedback gives the orientation in Euler angles in degrees, which were converted to quaternion)

The orientations are the same, while there is small difference in the positions.  The reason would be the reference frame is different.
Then which frame is the reference of RefreshFeedback?

I think this is an important question since such a reference frame should be commonly used in other services such as PlayCartesianTrajectory.

Thanks!
--Akihiko

Update:
When the robot is straight (`q=[  2.5679e-03   6.2816e+00   3.1687e+00   6.2675e+00   1.5262e-02   6.2823e+00   1.5847e+00]`),
KDL: `x=[  6.7176e-03   1.1250e-03   1.1873e+00   5.3245e-03   5.2877e-03   6.8599e-01   7.2757e-01]`
RefreshFeedback: `[  8.5176e-03   1.0656e-03   1.3073e+00   5.3246e-03   5.2877e-03    6.8599e-01   7.2757e-01]`
Since the robot total length is 1187.3 mm, the KDL result is correct.

**Comment by alexvannobel** [comment]
Hi @akihikoy ,

Do you have a Robotiq gripper installed on your arm? On boot-up, the robot detects whether or not the gripper is connected and sets the tool offset (not exposed by the API as of 1.1.7, but will be as of the next release) accordingly. 
If the gripper is currently connected on your arm, can you try the same experiment without the gripper? Are the results the same?

Cheers,
Alex

**Comment by akihikoy** [comment]
Although the version is updated to 2.0.0, this issue/question still exists.

Now the `RefreshFeedback` service will correspond with `base.tool_pose_*` elements of the `/my_gen3/base_feedback` topic.

I changed the gripper setting from the web interface; `End Effector Type = Not Installed`.
But it did not solve the issue.

For a better understanding, I visualized the two Cartesian poses;
Red cube: pose computed by KDL (`base_link='base_link', end_link='end_effector_link'`) with the current joint status.
Blue cube: pose obtained from `base.tool_pose_*` of the `/gen3a/base_feedback` topic.
Video: 
https://youtu.be/hIsr0LnbNGg

The robot is operated by the wrist-teaching button for translation, and the pose controller of the web interface for rotation.
Since during the rotation, the blue cube does not move, the Cartesian controller of the web interface looks using the tool pose.

My question is simple: what is the tool pose? and where is it defined?

**Comment by alexvannobel** [comment]
Hi @akihikoy ,

I believe there is a discrepancy between the URDF file and definition of the TCP inside the arm and the URDF file and TCP used by ROS (and MoveIt). I think this is why KDL and the base_feedback don't have the same values.
I'll talk to the Control team about the TCP definition inside the arm to see what are the changes we need to make in the ROS URDF, but I think it will only be a matter of adapting a couple reference frame offsets.
 
I'll update you soon on this issue.
Best,
Alex

**Comment by juntuck** [comment]
Hi @akihikoy ,
Could your issue be related to mine? #60

**Comment by alexvannobel** [comment]
Hi @akihikoy and @juntuck ,

The arm's firmware has some hardcoded values for end-effectors and tool frames. I added those frames to the xacro's and the tool_frame link should now correctly reflect the robot's feedback. It was also added to the arm move_group in MoveIt for every arm type.

I'll close the issue now but don't hesitate to reopen if you have questions!
Best,
Alex

**Comment by elevenjiang1** [comment]
> Hi @akihikoy and @juntuck ,
> 
> The arm's firmware has some hardcoded values for end-effectors and tool frames. I added those frames to the xacro's and the tool_frame link should now correctly reflect the robot's feedback. It was also added to the arm move_group in MoveIt for every arm type.
> 
> I'll close the issue now but don't hesitate to reopen if you have questions!
> Best,
> Alex

Hello,I want to know how to change this value of xacro file.By the way ,I want to know which is accuracy,xacro or base_feedback ?
This image the left is calculcate by KDL and right one is from the feedback.
![Screenshot from 2021-02-06 22-42-08](https://user-images.githubusercontent.com/43636049/107121518-d9682e80-68cd-11eb-9661-9d06e955e40f.png)
