### ISSUE TITLE
catkin_make fails in ubuntu 18.04, ros melodic branch of kortex 

### ISSUE THREAD

**Issue by apalapramanik** [Kinovarobotics/ros_kortex#266]
![issue](https://user-images.githubusercontent.com/50993551/202572130-26d01a26-1bfa-4ad8-8f31-d1884c6cf440.png)

**Comment by felixmaisonneuve** [comment]
Hi @apalapramanik,
 
Can you give the output of `conan remote list` and `conan --version`

Also, what command are you running to get this error?
Can you copy and paste the full output after the command?

Best,
Felix

**Comment by apalapramanik** [comment]
![issue5](https://user-images.githubusercontent.com/50993551/202584099-e2496849-7fd0-410a-b4c5-99285bc9a941.png)

I restarted the computer and build my package again so catkin_make works fine now. Not sure what caused the problem. Attached are the command outputs asked for.

**Comment by felixmaisonneuve** [comment]
Probably has to do with computer having to reboot after installing or changing some configuration in conan. 

If it works, I will close the issue

Best regards,
Felix
