### ISSUE TITLE
I first go from A to C, with tool(default){0,0,0.2,0,0,0}, then set tool {0,0.3,0.2,0,0,0} then go from C to D, with with tool(set){0,0.3,0.2,0,0,0},error!!!!!!!!!!!!

### ISSUE THREAD

**Issue by wentianheshi** [Kinovarobotics/ros_kortex#277]
error:
![企业微信截图_1675250638446](https://user-images.githubusercontent.com/38513139/216031023-2bc85526-ff49-46e5-bdb2-0a12a6b666e2.png)
code:
/*
 * KINOVA (R) KORTEX (TM)
 *
 * Copyright (c) 2019 Kinova inc. All rights reserved.
 *
 * This software may be modified and distributed
 * under the terms of the BSD 3-Clause license.
 *
 * Refer to the LICENSE file for details.
 *
 */

**Comment by felixmaisonneuve** [comment]
Hi @wentianheshi,

I won't debug a 700 line file you wrote. Maybe you could guide me to the specific section you are having trouble with.

Based on your terminal output, your waypoint list is invalid. You can use the `ValidateWaypointList` function and print the errors in your waypoint list.

Best,
Felix

**Comment by wentianheshi** [comment]
sorry  Felix 
Previously, your reply to me was based on the SDK, now it is based on ROS questions.
I want say :
case1: I set three waypoint A,B,C,and let robot move A to B to C is successed 
case2:  
first i control robot move A to B then I set tool transform(0,0.01,0,0,0,0)  finally I control robot B to C  failed 
![image](https://user-images.githubusercontent.com/38513139/216247420-909b5946-3d1c-4d1a-820a-ce178d66b728.png)
As can be seen from the logs, the robot received an abort command，
So I suspect the  function of tool_transform have some error.
**the code of  tool_transform**
#include <kortex_driver/SetToolConfiguration.h>

bool example_set_tool_transform(ros::NodeHandle n,
                                const std::string &robot_name) {
  ros::ServiceClient service_client_set_cartesian_tool_transform =
      n.serviceClient<kortex_driver::SetToolConfiguration>(
          "/" + robot_name + "/control_config/set_tool_configuration");
  kortex_driver::SetToolConfiguration service_set_cartesian_tool_transform;

  service_set_cartesian_tool_transform.request.input.tool_transform.x = 0;
  service_set_cartesian_tool_transform.request.input.tool_transform.y = 0.01;
  service_set_cartesian_tool_transform.request.input.tool_transform.z = 0;
  service_set_cartesian_tool_transform.request.input.tool_transform.theta_x = 0;
  service_set_cartesian_tool_transform.request.input.tool_transform.theta_y = 0;
  service_set_cartesian_tool_transform.request.input.tool_transform.theta_z = 0;

  if (!service_client_set_cartesian_tool_transform.call(
          service_set_cartesian_tool_transform)) {
    std::string error_string = "Failed to call SetToolConfiguration";
    ROS_ERROR("%s", error_string.c_str());
    return false;
  }
  ROS_INFO("set tool success");

  // Wait a bit
  std::this_thread::sleep_for(std::chrono::milliseconds(250));

  return true;
} 

In order to test tool_transform function ，I put this function into the following three cpp files
![image](https://user-images.githubusercontent.com/38513139/216262328-4463d35e-5322-4b56-a90a-7f37b29a190d.png)
catkin_make
only example_waypoint_action_client.cpp can run success but kinova driver log have
some error
![image](https://user-images.githubusercontent.com/38513139/216263064-61027aca-c0bc-42cf-ada9-f7be89a0c7a1.png)
other two cpp file run abort  
![image](https://user-images.githubusercontent.com/38513139/216263501-edac07b5-9c10-4df5-a07b-b78ae7f9dc8b.png)

Please give me some professional advice
thanks
wentianheshi

**Comment by wentianheshi** [comment]
i also test code 
success &= example_send_cartesian_pose(n, robot_name, 0.1, 0, 0, 0, 0, 0);
success &= example_send_cartesian_pose(n, robot_name, 0, 0, 0, 0, 0, 0);
success &= example_send_cartesian_pose(n, robot_name, -0.1, 0, 0, 0, 0, 0);
success &= example_set_tool_transform(n, robot_name);
this process is successed

**Comment by felixmaisonneuve** [comment]
Hi @wentianheshi,

So I have tried moving the arm between 3 poses like you did and setting your tool configuration between the second and third action.
Everything worked great for me. No ACTION_ABORT.

Looking at your log, I find it strange that you received an ACTION_ABORT for action 1001. You received an ACTION_END for action 1001 (Pose 1) just before. You then send Pose 12 to the arm, so I would expect a different action identifier. Are you sure about this piece of code?

Also, have you tried using other poses?

Best,
Felix

**Comment by wentianheshi** [comment]
Hi @Felix
First，Thank you for your reply.
I guss the process of setting  tool configuration must wait the point moved success，so the process of moving point A to point B must used action client in ros.   
The method described in the image is not suitable
![image](https://user-images.githubusercontent.com/38513139/217222954-26a77ce6-8978-462c-840e-0054049c4682.png)
can you send me a copy of your testing program, I can compare the differences between the two, maybe this may help me the most.

**Comment by felixmaisonneuve** [comment]
Yes, I just tested it and changing the tool configuration during an action will lead to an action abort. You have to wait until the action is finished, then change the tool configuration, then start your new action. 

You cannot do both at the same time
