### ISSUE TITLE
ROS2 support?

### ISSUE THREAD

**Issue by AlfaKeNTAvR** [Kinovarobotics/ros_kortex#295]
Are there any plans or existing repositories for ROS2 support?

**Comment by felixmaisonneuve** [comment]
Hi @AlfaKeNTAvR,

There is already a thread on this topic : #69 

The answer is still the same as my [previous answer](https://github.com/Kinovarobotics/ros_kortex/issues/69#issuecomment-1255265858)

>We can confirm a ROS2 implementation will be done for Gen3, but do not have a release timeline yet

Regards,
Felix

**Comment by phuicy** [comment]
Try this as a stand in: https://github.com/phuicy/Kinova-Torque-Control
