### ISSUE TITLE
EndEffector_Link.STL malformed

### ISSUE THREAD

**Issue by AshisGhosh** [Kinovarobotics/ros_kortex#3]
Upon opening the gen3 arm in rviz:
```
The STL file 'package://kortex_description/meshes/EndEffector_Link.STL' is malformed.
It appears to be a binary STL file but does not contain enough data for the 
80 byte header and 32-bit integer triangle count.
```
and
```
Could not load model 'package://kortex_description/meshes/EndEffector_Link.STL' for link 
'EndEffector_Link': OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource 
package://kortex_description/meshes/EndEffector_Link.STL in resource group Autodetect or 
any other group. in ResourceGroupManager::openResource at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
```

Cheers,
Ashis

**Comment by alexvannobel** [comment]
Hi @AshisGhosh ,

Thanks again for the feedback.
We are aware of this STL file causing problems and are working on cleaning the kortex_description package a bit. 
The EndEffector link is technically just a point at the end of the arm, so specifying a mesh file, either for the geometry or the collision, is not mandatory.
While the fix isn't pushed, a good workaround here to load the robot description properly would be to comment or simply remove the [geometry mesh file loading](https://github.com/Kinovarobotics/ros_kortex/blob/master/kortex_description/urdf/JACO3_URDF_V10.urdf#L461-L464) and the [collision mesh file loading](https://github.com/Kinovarobotics/ros_kortex/blob/master/kortex_description/urdf/JACO3_URDF_V10.urdf#L475-L478) from the URDF.

Hope this helps,
Cheers, 

Alex

**Comment by alexvannobel** [comment]
Hi @AshisGhosh ,

The latest push to the kinetic-devel branch fixed this issue in the [urdf](https://github.com/Kinovarobotics/ros_kortex/blob/kinetic-devel/kortex_description/arms/gen3/urdf/gen3_macro.xacro), by only declaring the link instead of loading an STL file for it. 

Cheers,
Alex
