### ISSUE TITLE
How to increase the max cartesian velocity speed?

### ISSUE THREAD

**Issue by IsaacSheidlower** [Kinovarobotics/ros_kortex#315]
Hello,

I have recently been using the cartesian velocity service for control, but need to increese its angular speed. I can figure out how to increase the joint speed for joint velocity control, and wehn using the xbox controller directly, can raise the speed of the cartessian control significantly faster than the default max in the cartesian velocity service. I have tried using the ChangeTwist action but that always returns an error.

Please advice. Thank you very much.

**Comment by martinleroux** [comment]
Hi,

You can use the SetTwistLinearSoftLimit service. Alternatively, you can also use the Web App in Configurations > Speed Limits > Advanced > Cartesian Joystick.

Cheers

**Comment by IsaacSheidlower** [comment]
Worked out! Also used AngularSoftLimit. Thank you very much!
