### ISSUE TITLE
Fail to catkin_make:   Problem about  protoc version 

### ISSUE THREAD

**Issue by Lueasecool** [Kinovarobotics/ros_kortex#324]
****This file was generated by an older version of protoc which is
/usr/include/gazebo11/gazebo/msgs/wrench_stamped.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
/usr/include/gazebo11/gazebo/msgs/wrench_stamped.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.****

****

## Version

ROS distribution : neotic

Branch and commit you are using : noetic-devel

I have try different version of protoc,such as 3.2.0,3.6.0,3.15.0. But it doesn't work ,I guess maybe the problem is that:
when I download ros-noetic-gazebo-ros-pkgs,the system ask me to download "protoc complier(3.6.1)",it doesn't compatible with my protoc which added in root system.But I don't know how to avoid this situation,I have to download gazebo-pkg but with a protoc complier .
![2024-06-02 16-42-09 的屏幕截图](https://github.com/Kinovarobotics/ros_kortex/assets/147911079/69317600-1ecf-4f20-9bc4-1b93fa90476b)
Hope Someone Can help me!

**Comment by smoya23** [comment]
Hi @Lueasecool ,

Could you try uninstalling it from your machine and trying a clean install again ? This issue was addressed in issues #56 and #23. Let me know if any of these solutions help you.

**Comment by martinleroux** [comment]
I will be closing this ticket due to inactivity. For full answers refer to the issues linked above.
