### ISSUE TITLE
activating the camera

### ISSUE THREAD

**Issue by malicbuk** [Kinovarobotics/ros_kortex#335]
Normally, gen3 has a camera but in gazebo , camera is not working. How can ı activate the camera or how can ı add camera to gen3?

**Comment by aalmrad** [comment]
Hello, 
In the current urdf of the robotic arm, a camera link is defined if you set the ${vision} parameter to "true" as you can see [here](https://github.com/Kinovarobotics/ros_kortex/blob/bf71d8ecdec874a88d02b1a2481784ae2a7fdba4/kortex_description/arms/gen3/7dof/urdf/gen3_macro.xacro#L315C4-L336)
However to activate a visual stream in the simulation environment you have to add a Gazebo plugin to the urdf of the robot. Please refer to the camera examples [here](https://classic.gazebosim.org/tutorials?tut=ros_gzplugins) for more details and let me know if you have any further questions.

Best,
Abed

**Comment by malicbuk** [comment]
the camera  came but the camera is looking to the grapper.How can ı fix that
    <xacro:if value="${vision}" >
      <link name="${prefix}camera_link" />
      <joint name="${prefix}camera_module" type="fixed">
        <origin xyz="0 0.05639 -0.00305" rpy="3.14159265358979 3.14159265358979 0" />
        <parent link="${prefix}end_effector_link" />
        <child  link="${prefix}camera_link" />
      </joint>
      <link name="${prefix}camera_depth_frame" />
      <joint name="${prefix}depth_module" type="fixed">
        <origin xyz="0.0275 0.066 -0.00305" rpy="3.14159265358979 3.14159265358979 0" />
        <parent link="${prefix}end_effector_link" />
        <child  link="${prefix}camera_depth_frame" />
      </joint>
      <link name="${prefix}camera_color_frame" />
      <joint name="${prefix}color_module" type="fixed">
        <origin xyz="0 0.05639 -0.00305" rpy="3.14159265358979 3.14159265358979 0" />
        <parent link="${prefix}end_effector_link" />
        <child  link="${prefix}camera_color_frame" />
      </joint>
	<gazebo reference="${prefix}camera_link">
	  <sensor type="camera" name="robot_camera">
	    <visualize>true</visualize>
	    <update_rate>30.0</update_rate>
	    <camera>
	      <horizontal_fov>1.3962634</horizontal_fov>
	      <image>
		<width>800</width>
		<height>800</height>
		<format>R8G8B8</format>
	      </image>
	      <clip>
		<near>0.02</near>
		<far>300</far>
	      </clip>
	    </camera>
	    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
	      <alwaysOn>true</alwaysOn>
	      <updateRate>0.0</updateRate>
	      <cameraName>robot_camera</cameraName>
	      <imageTopicName>camera/image_raw</imageTopicName>
	      <cameraInfoTopicName>camera/camera_info</cameraInfoTopicName>
	      <frameName>camera_link</frameName>
	    </plugin>
	  </sensor>
	</gazebo>
      
    </xacro:if>
this is the code
![default_gzclient_camera(1)-2024-09-18T17_24_16 034475](https://github.com/user-attachments/assets/e7b2b10a-1e4c-4684-8641-efe9eeb1ddf8)
![default_gzclient_camera(1)-2024-09-18T17_24_01 607848](https://github.com/user-attachments/assets/80b1beef-1339-486a-9fe5-7ed6d614298a)

**Comment by malicbuk** [comment]
the camera came but the camera is looking to the right. How can ı fix that.
  <xacro:if value="${vision}" >
      <link name="${prefix}camera_link" />
      <joint name="${prefix}camera_module" type="fixed">
        <origin xyz="0 0.05639 -0.00305" rpy="3.14159265358979 3.14159265358979 0" />
        <parent link="${prefix}end_effector_link" />
        <child  link="${prefix}camera_link" />
      </joint>
      <link name="${prefix}camera_depth_frame" />
      <joint name="${prefix}depth_module" type="fixed">
        <origin xyz="0.0275 0.066 -0.00305" rpy="3.14159265358979 3.14159265358979 0" />
        <parent link="${prefix}end_effector_link" />
        <child  link="${prefix}camera_depth_frame" />
      </joint>
      <link name="${prefix}camera_color_frame" />
      <joint name="${prefix}color_module" type="fixed">
        <origin xyz="0 0.05639 -0.00305" rpy="3.14159265358979 3.14159265358979 0" />
        <parent link="${prefix}end_effector_link" />
        <child  link="${prefix}camera_color_frame" />
      </joint>
	<gazebo reference="${prefix}camera_link">
	  <sensor type="camera" name="robot_camera">
	    <visualize>true</visualize>
	    <update_rate>30.0</update_rate>
	    <camera>
	      <horizontal_fov>1.3962634</horizontal_fov>
	      <image>
		<width>800</width>
		<height>800</height>
		<format>R8G8B8</format>
	      </image>
	      <clip>
		<near>0.02</near>
		<far>300</far>
	      </clip>
	    </camera>
	    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
	      <alwaysOn>true</alwaysOn>
	      <updateRate>0.0</updateRate>
	      <cameraName>robot_camera</cameraName>
	      <imageTopicName>camera/image_raw</imageTopicName>
	      <cameraInfoTopicName>camera/camera_info</cameraInfoTopicName>
	      <frameName>camera_link</frameName>
	    </plugin>
	  </sensor>
	</gazebo>
      
    </xacro:if>
this is code where you mentioned. I add my code.
![default_gzclient_camera(1)-2024-09-18T17_24_16 034475](https://github.com/user-attachments/assets/f8965e68-d0f1-44de-992c-5c9b0948126c)
![default_gzclient_camera(1)-2024-09-18T17_24_01 607848](https://github.com/user-attachments/assets/eb04044c-2384-4801-a807-6b16196b11e6)

**Comment by malicbuk** [comment]
![default_gzclient_camera(1)-2024-09-18T17_24_16 034475](https://github.com/user-attachments/assets/77750797-6f39-458d-a4f2-0866f87a3a9b)
![default_gzclient_camera(1)-2024-09-18T17_24_01 607848](https://github.com/user-attachments/assets/924ef2e4-4409-47ea-93bd-4a6b6921243b)
