### ISSUE TITLE
integrate d455 camera

### ISSUE THREAD

**Issue by malicbuk** [Kinovarobotics/ros_kortex#336]
I want to integrate d435 camera to gen3 . How can ı do?

**Comment by martinleroux** [comment]
The Gen3 cannot support other cameras. Your only option is to design a mounting bracelet and guide wires outside the robot.

**Comment by malicbuk** [comment]
in the simulation gazebo and rviz , ı want to just try the d435 wit gen3. Is that impossible?

**Comment by martinleroux** [comment]
Our package offers no built-in function to assist with the integration of cameras. I suggest looking at the realsense ROS package, which you can find [here](https://github.com/pal-robotics/realsense_gazebo_plugin).
