### ISSUE TITLE
Force on the gripper

### ISSUE THREAD

**Issue by atabakd** [Kinovarobotics/ros_kortex#41]
I have a `2F-85` gripper and I looked at the updated release `v2.0.0`.
I noticed there is a new information in the rostopic called `joint_states` about `effort` on the gripper.
However, the value of this quantity is always fixed at zero, even though we applied force at the fingers.

![image](https://user-images.githubusercontent.com/5020822/65353264-9af0a780-dbe4-11e9-8349-afe936fcacbe.png)

Is this the expected behaviour? Is it possible to somehow read this value? For example, in order to have a force control loop.
Thanks

**Comment by simonferronforget** [comment]
Hello Atabak, 
Effort data coming from the gripper is currently not supported in Kortex Arm Driver: effort will remain 0 for all gripper joint states.

However, note that the Robotiq 2F-85 gripper itself is not equipped with torque sensors.

Hope this helps.

Simon
