### ISSUE TITLE
rostopic for cartesian velocity and joint velocity commands

### ISSUE THREAD

**Issue by abhishekpadalkar** [Kinovarobotics/ros_kortex#50]
It would be nice if we can send joint velocity and cartesian velocity commands using rostopics instead of services.

**Comment by alexvannobel** [comment]
Hi @abhishek098 ,

I just merged a PR to send joint speeds and twists directly to the arm. 
The details are in the [readme](https://github.com/Kinovarobotics/ros_kortex/tree/kinetic-devel/kortex_driver#robot-control-topics-in).

I'll close this issue but feel free to reopen it if you experience problems with it.

Best regards, 
Alex
