### ISSUE TITLE
control  problems

### ISSUE THREAD

**Issue by WHGang** [Kinovarobotics/ros_kortex#63]
Hello, I saw a [video](https://www.youtube.com/watch?v=8MTuTNIQUqA) on YouTube.  At the end of the view, gen3 can realize follow the goal in real time. I want to know how is it controlled?  Thanks!

**Comment by WHGang** [comment]
![Screenshot from 2019-12-13 11-08-37](https://user-images.githubusercontent.com/43157028/70766578-29666680-1d99-11ea-8c0e-8c58ad2ebaef.png)
just like jaco2!

**Comment by alexvannobel** [comment]
Hi @WHGang ,

I just merged #72 that enables sending joint speed and twist as a topic to the arm. You will find the details in the [readme](https://github.com/Kinovarobotics/ros_kortex/tree/kinetic-devel/kortex_driver#robot-control-topics-in).

I'll close this issue, but feel free to reopen it if you experience problems wiht it. 

Best regards, 
Alex
